apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-sample-app
  template:
    metadata:
      labels:
        app: secret-sample-app
    spec:
      containers:
        - name: secret-sample-app
          image: registry.digitalocean.com/k6ps-container-registry/secret-sample-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MY-ENV
              value: "" # Patched in overlays
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
